dotenv: .env

wallet:
  from_key: ${PRIVATE_KEY}

networks:
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True

  development:
    verify: False